ignore:
  - "extern/**/*"
  - "apps/gen_po_moving_block_astar_testing.cpp"
  - "apps/gen_po_moving_block_mip_testing.cpp"
  - "apps/vss_generation_timetable_mip_testing.cpp"
  - "test/**/*"
  - "test/*"

coverage:
  range: 60..90
  precision: 1
  status:
    project:
      default:
        threshold: 0.5%
    patch:
      default:
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
