name: C++

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 3

jobs:
  cpp-tests:
    name: Tests ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, toolchain: "" }
          - { os: macos-latest, toolchain: "" }
          - { os: windows-latest, toolchain: "-T ClangCl" }
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - shell: bash
        id: install-gurobi
        env:
          VERSION: 10.0.2
        run: |
          wget https://packages.gurobi.com/10.0/gurobi10.0.2_linux64.tar.gz
          tar -xvzf gurobi10.0.2_linux64.tar.gz
          rm -rf gurobi10.0.2_linux64.tar.gz
          ls . 
      - shell: bash
        id: write-license
        env:
          LICENSE: ${{ secrets.LICENSE   }}
        run: |
          echo "$LICENSE" > $PWD/gurobi.lic
          echo "grb_license_file=$PWD/gurobi.lic" >> $GITHUB_OUTPUT
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ${{ matrix.config.toolchain }}
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        run: ctest -C Release --output-on-failure --test-dir build --repeat until-pass:3 --timeout 300
      - if: runner.os == 'Linux'
        name: Coverage
        run: |
          cmake -S . -B buildCov -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON
          cmake --build buildCov --config Debug
          ctest -C Debug --output-on-failure --test-dir buildCov --repeat until-pass:3 --timeout 300
      - if: runner.os == 'Linux'
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          fail_ci_if_error: true
          flags: cpp
          gcov: true
          gcov_ignore: "extern/**/*"
          token: ${{ secrets.CODECOV_TOKEN }}
