name: ubuntu

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 3
  GUROBI_VERSION_SHORT: "10.0"
  GUROBI_VERSION: "10.0.2"
  GUROBI_VERSION_FOLDER: "gurobi1002"

jobs:
  cpp-tests-ubuntu:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup-gurobi-license
        id: write-license
        env:
          GUROBI_LICENSE: ${{ secrets.GUROBI_LICENSE   }}
        run: |
          echo "$GUROBI_LICENSE" > $PWD/gurobi.lic
          echo "GRB_LICENSE_FILE=$PWD/gurobi.lic" >> $GITHUB_ENV
      - name: download-gurobi-linux
        env:
          GUROBI_FILE: gurobi${{ env.GUROBI_VERSION }}_linux64.tar.gz
        run: |
          wget https://packages.gurobi.com/${{ env.GUROBI_VERSION_SHORT }}/${{ env.GUROBI_FILE }}
          tar -xvzf ${{ env.GUROBI_FILE }}
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ${{ matrix.config.toolchain }}
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        run: ctest -C Release --output-on-failure --test-dir build --repeat until-pass:3 --timeout 300
  call-macos:
    uses: ./.github/workflows/macos.yml
